const express = require("express")
const verifyToken = require("../middlewares/verifyToken")
const organizerController = require("../controllers/organizer.controller")
const router = express.Router()
const allowedTo = require("../middlewares/allowedTo")
const userRoles = require("../utils/userRole")